---
apiVersion: v1
kind: Secret
metadata:
  name: orderss33-app-repo
  namespace: devhub2
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/devhub-mad/orderss33-app-backend-gitops
